apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: transcriberapp-audios
  namespace: transcriber
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: transcriberapp-transcripts
  namespace: transcriber
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: transcriberapp-outputs
  namespace: transcriber
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
